version: 2
sources:
  - name: local_bike
    schema: local_bike

    tables:
    - name: orders
    - name: order_items
    - name: products
    - name: categories
    - name: stocks
    - name: customers
    - name: staffs
    - name: stores
    - name: brands
